name: Run Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: xcodebuild test -scheme MijickPopups -destination 'platform=iOS Simulator,OS=18.5,name=iPhone SE (3rd generation)'
