name: Run Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ios-18
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: xcodebuild test -scheme MijickPopups -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 13 Pro'
